---
title: "Project Proposal"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
The knitted .html file should contain:

The names of the students in the group.

A brief description of how the group will communicate and work together.
When during the week can the group meet? Consider needs of all group members.
What platforms will the group use to communicate and share documents?

The question or questions of interest that motivate the planned study.
The topic selected must be unanimous among group members.
See "Question of Interest" above.

Links to where one can find and download the dataset(s) you are going to use. Please confirm that you can read the data into RStudio. 

A description of the data:
Who collected the data? 
How were the data collected? (Note: Just stating that "you found the dataset on Kaggle" or similar is not enough. If the dataset does not document how it was collected, you should either change to a new dataset, or describe important questions you have about the collection process which remain unanswered.) 
What are the key variables in the data set, what do they measure, and how are they related to your key questions? (You do not have to describe variables which you will not use for your question of interest.)
What does a single row of the data set represent in real terms? (E.g. One row of the dataset represents one winter season where Lake Monona froze over.)
If the data is a sample from some larger population, what is that larger population?
 

Include a description of a graph which will show how the data informs the primary question of interest.
Describe what variables you will include and what type of graph you will create.
You do not have to create the graph just yet, only a description is required.
 

Finally, please do your best to identify which type of inference method you are going to use. In particular, please identify one of the inference methods listed below, and which variable(s) are your cause and effect (if applicable)
Simple linear regression (Using a continuous variable X to predict a continuous variable Y)
Inference on a single population proportion (is it equal to some value of interest?) or difference of two population proportions
Inference on a single population mean (is it equal to some value of interest?) or difference of two population means 

## Project Members & Communication
Sheryl Wang, Luke Morrison, Camden Cobb, Cameron Maricque

In order to communicate with each other, we plan to use our .wisc emails and an Outlook group to communicate asynchronously about project details. 
We also created a github repository with each group member having collaborator access so that we can edit our R Markdown and HTML files seperately;
this means that it is less necessary to schedule physical meet ups which is difficult with everyone's schedules. 

In order to ensure that we maintain high quality code without in-person meetings we can Code Review by: 
 - Each team member reviewing another's code
   - Documentation of reviewing findings
  

## Question of Interest
What is the relationship between passenger age and survival probability on the Titanic, and can we use this relationship to predict survival chances for passengers of different ages? 


## Data
Link to data: https://github.com/awesomedata/awesome-public-datasets/tree/master/Datasets

Description of data:
Data Collection and Source:
   The Titanic dataset was compiled from historical passengers and official records of the RMS Titanic's maiden voyage in 1912. The primary source materials are: 
1. Official passenger manifests 
2. Encyclopedia Titanica 
3. Survival records from the disaster 
4. Ticket purchasing recrods and boarding documents 

Unit Of Observation:
Each Row in the dataset represents one individual passenger aboard the Titanic's maiden voyage. 

Population:
The dataset represents the complete population of all documented passengers aboard the Titanic (not just a sample) 

What are Our Key Variables: 
1. Age: 
Continous numerical variable, measured by passenger's age in years. 
Missing values present: yes 

2. Survived 
Type: Binary categorical variable
Bernoulli: 0 = did not survive 1 = Survived 
No missing values for this 
This is our dependent variable

## Graph/Visualization
Primary Visualization:
We will create a Scatter Plot with our x-axis as age (0-80) and Y axis (0 or 1) We can also create an age distribution subplot to make a histogram fora age distribution with seperate colors for survivors and non-survivors to help enhance visualizing age-related survival patterns. 
We could add vertical reference lines for meaninful age boundaries (18 for children, 65 for seniors) 
In order to make the experiment more complex, we could add a Prediction interval with a light red shade which would show the 95% prediction interval 


## Inference method
Our inference method will be: Linear Regression.
Independent (X): Age (continuous)
Dependent (Y): Survival status (binary: 0/1)

Justification:
1. While our dependent variable is binary, we belive linear regression can still provide meaningful insights about probability of survival.
2. Age being continuous as our predictor makes linear regression appropriate. 
3. The coefficients will give a clear sign as change in survival probability per year of age. 

We will supplement our Linear Regression with a prediction interval at 95% 


